services:
  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - appnet    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    tty: true
    depends_on:
      - app

  app:
    image: node:15
    working_dir: /app
    container_name: app
    volumes:
      - .:/app    
    expose:
      - 3000
    networks:
      - appnet
    command: node index.js

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 30s
    depends_on:
      - app

networks:
  appnet:
    driver: bridge